### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by Cheyans** [ripples/lv-client#4]

**Comment by marymoser** [comment]
Some of my original (fancier) ideas for login:
One would be combining it with the landing and/or home page. This particular image shows the top of a sample landing page. (Mentally insert some image/pattern in place of the gradient background, plus more text/content below.) Users can have immediate access to the login form.
![bw_landing_view_1](https://cloud.githubusercontent.com/assets/11800862/16174223/40a0c640-3587-11e6-8628-17918fa42c04.png)
Otherwise, we can have the login as a simple, single-page view (no scrolling). The form itself can be wrapped inside a traditional, central div (certainly good enough for a prototype), or else do something clever with the layout/background. (I haven't designed a wireframe for the first case, but I certainly can, although I think most people get the idea.) 
![bw_landing_view_2](https://cloud.githubusercontent.com/assets/11800862/16174224/44be8c6c-3587-11e6-97a9-aa58dd04d41b.png)
Both images were designed with the idea that the login would be combined with the "landing page" (i.e. it'd be the first thing that a logged-out user would come to), then after logging in you may end up at some generic starting/interaction point like the Feed page (similar to how Facebook takes you directly to your newsfeed). However, if an actual home page is envisioned (as suggested by the Github issue), then another option is to simply have a link to the login page from the home page (unless home is not authorized for logged out users).
