### ISSUE TITLE
Media Page

### ISSUE THREAD

**Issue by Cheyans** [ripples/lv-client#7]
![image](https://cloud.githubusercontent.com/assets/8811789/16141332/724a5fcc-3428-11e6-9821-d287a24e88ba.png)
![image](https://cloud.githubusercontent.com/assets/8811789/16141335/7439f338-3428-11e6-80ce-4286a25b2848.png)
![image](https://cloud.githubusercontent.com/assets/8811789/16141336/7645b342-3428-11e6-9a90-0602091b4df0.png)

**Comment by timdrichards** [comment]
I think the top version is the one that is most clean. I look forward to what other people think. I really like this wireframes!

**Comment by timdrichards** [comment]
I also like the breadcrumbs at the top to see which semester, course, and lecture you are viewing.

**Comment by Cheyans** [comment]
I think the second one is better, they get a preview of the whiteboard and computer screen.

**Comment by marymoser** [comment]
In response to Cheyan's post: I probably could have made it more obvious, but the idea with the first design is you can still preview the whiteboard/slides, if you go to the "Media" tab. Basically the concept was rather than having a timeline as a sidebar and switchable media as a "footer", you could combine them (and anything else the user might want to use) into one element and just switch between tabs depending on what you want to view/interact with. The disadvantage, obviously, is that you can't see/interact both tabs at once (unless we come up with a creative way to do that...), which may slow down the interactivity of the user; the advantage is mostly to save space (which, as Tim mentioned, can help make it look cleaner) and permit a larger (and thus more visible) video frame.

**Comment by Cheyans** [comment]
One thing we can do, but I'm not exactly sure how, is to do a youtube style player where rather than having dedicated screen space for the timeline, we just have it so if they hover over a time on the navigation bar we show a small preview of the current media source. Also, for the transcript we would have to use some sort of speech recognition technology unless professors want to provide something, I think that is outside the scope of this project until further notice.
